window.ORS_API_KEY = "eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImIzM2U2Y2E1NDc0YjQ0MDc4NjFiZTY2YmE2MDQyOTdkIiwiaCI6Im11cm11cjY0In0";

console.log("CONFIG GELADEN");
console.log(window.ORS_API_KEY);
